export const AUTH = {
  LOGIN_PENDING: "AUTH_LOGIN_PENDING",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
}

export const ALERT = {
  ACTIVE: "ALERT_ACTIVE",
  CLOSE: "ALERT_CLOSE",
}

export const TAG = {
  GET_ALL_TAGS_PENDING: "GET_ALL_TAGS_PENDING",
  GET_ALL_TAGS_SUCCESS: "GET_ALL_TAGS_SUCCESS",
  GET_ALL_TAGS_FAILED: "GET_ALL_TAGS_FAILED",
  CREATE_TAG_PENDING: "CREATE_TAG_PENDING",
  CREATE_TAG_SUCCESS: "CREATE_TAG_SUCCESS",
  CREATE_TAG_FAILED: "CREATE_TAG_FAILED",
  DELETE_TAG_PENDING: "DELETE_TAG_PENDING",
  DELETE_TAG_SUCCESS: "DELETE_TAG_SUCCESS",
  DELETE_TAG_FAILED: "DELETE_TAG_FAILED",
}

export const MODAL = {
  ACTIVE: "MODAL_ACTIVE",
  CLOSE: "MODAL_CLOSE",
  PENDING: "MODAL_PENDING",
  SUCCESS: "MODAL_SUCCESS",
}
